const {neon}=require("@neondatabase/serverless");
const webpush=require("web-push");
let sqlClient=null;
function getDb(){if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL belum dikonfigurasi.");if(!sqlClient)sqlClient=neon(process.env.DATABASE_URL);return sqlClient;}
function configureVapid(){const s=process.env.VAPID_SUBJECT,p=process.env.VAPID_PUBLIC_KEY,k=process.env.VAPID_PRIVATE_KEY;if(!s||!p||!k)throw new Error("Konfigurasi VAPID belum lengkap.");webpush.setVapidDetails(s,p,k);}
function json(res,status,payload){res.status(status).setHeader("Content-Type","application/json; charset=utf-8");res.setHeader("Cache-Control","no-store");return res.json(payload);}
function methodOnly(req,res,m){if(req.method!==m){json(res,405,{error:"Method tidak diizinkan."});return false;}return true;}
function parseBody(req){if(req.body&&typeof req.body==="object")return req.body;if(typeof req.body==="string"&&req.body.trim()){try{return JSON.parse(req.body)}catch(_){}}if(req.body===undefined)return {};throw new Error("JSON body tidak valid.");}
function requireSameOrigin(req,res){const o=req.headers.origin;if(!o)return true;const proto=String(req.headers["x-forwarded-proto"]||"https").split(",")[0].trim(),host=String(req.headers.host||"").split(",")[0].trim();if(host&&o===`${proto}://${host}`)return true;json(res,403,{error:"Origin tidak diizinkan."});return false;}
function cleanString(v,max,f=""){return String(v??f).trim().slice(0,max);}
function validateDeviceId(v){const id=cleanString(v,128);if(!/^[A-Za-z0-9._:-]{16,128}$/.test(id))throw new Error("deviceId tidak valid.");return id;}
function validateTimezone(v){const tz=cleanString(v,80,"Asia/Jakarta");try{new Intl.DateTimeFormat("en-US",{timeZone:tz}).format(new Date());return tz;}catch(_){return "Asia/Jakarta";}}
function parseTime(v){const m=String(v||"").match(/^([01]\d|2[0-3]):([0-5]\d)$/);return m?{hour:Number(m[1]),minute:Number(m[2])}:null;}
function addLocalDays(p,n){const d=new Date(Date.UTC(p.year,p.month-1,p.day+n,12));return {year:d.getUTCFullYear(),month:d.getUTCMonth()+1,day:d.getUTCDate()};}
function diffLocalDays(a,b){return Math.round((Date.UTC(a.year,a.month-1,a.day)-Date.UTC(b.year,b.month-1,b.day))/86400000);}
function dayOfWeek(p){return new Date(Date.UTC(p.year,p.month-1,p.day)).getUTCDay();}
function zonedParts(date,tz){const ps=new Intl.DateTimeFormat("en-US",{timeZone:tz,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(date);const o={};for(const p of ps)if(p.type!=="literal")o[p.type]=p.value;return {year:Number(o.year),month:Number(o.month),day:Number(o.day),hour:Number(o.hour),minute:Number(o.minute),second:Number(o.second)};}
function localAsUtcMs(p){return Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second);}
function zonedLocalToUtcMs(local,tz){let g=localAsUtcMs(local);for(let i=0;i<5;i++){const a=zonedParts(new Date(g),tz),d=localAsUtcMs(local)-localAsUtcMs(a);if(!d)break;g+=d;}return g;}
function reminderOffsetMinutes(v){return v==="10m"?10:v==="30m"?30:0;}
function isScheduledOnLocalDate(r,d){const w=dayOfWeek(d);if(r.recurrence==="daily")return true;if(r.recurrence==="weekdays")return w>=1&&w<=5;if(r.recurrence==="weekly")return r.days.includes(w);if(r.recurrence==="custom"){const step=Math.max(1,Number(r.customEvery||1))*(r.customUnit==="weeks"?7:1),diff=diffLocalDays(d,r.createdAtLocalDate);return diff>=0&&diff%step===0;}return false;}
function nextReminderAt(r,afterDate=new Date()){if(!r.active||r.reminder==="off")return null;const t=parseTime(r.time);if(!t)return null;const tz=validateTimezone(r.timezone),now=zonedParts(afterDate,tz),start={year:now.year,month:now.month,day:now.day},after=afterDate.getTime();for(let i=0;i<=730;i++){const d=addLocalDays(start,i);if(!isScheduledOnLocalDate(r,d))continue;const target=zonedLocalToUtcMs({...d,hour:t.hour,minute:t.minute,second:0},tz),run=target-reminderOffsetMinutes(r.reminder)*60000;if(run>after)return new Date(run);}return null;}
function normalizeReminder(raw){const id=cleanString(raw?.id,120),title=cleanString(raw?.title,80,"Targetku"),body=cleanString(raw?.body,250,"Saatnya menjalankan target."),time=cleanString(raw?.time,5),recurrence=["daily","weekdays","weekly","custom"].includes(raw?.recurrence)?raw.recurrence:"daily",reminder=["off","atTime","10m","30m"].includes(raw?.reminder)?raw.reminder:"off",days=Array.isArray(raw?.days)?[...new Set(raw.days.map(Number).filter(n=>Number.isInteger(n)&&n>=0&&n<=6))]:[],customEvery=Math.min(30,Math.max(1,Number(raw?.customEvery||1))),customUnit=raw?.customUnit==="weeks"?"weeks":"days",createdAt=Number(raw?.createdAt||Date.now());if(!id)throw new Error("Reminder id wajib.");if(!parseTime(time))throw new Error("Format waktu harus HH:MM.");if(recurrence==="weekly"&&!days.length)throw new Error("Weekly membutuhkan minimal satu hari.");if(!Number.isFinite(createdAt))throw new Error("createdAt tidak valid.");const timezone=validateTimezone(raw?.timezone),created=new Date(createdAt),p=zonedParts(Number.isNaN(created.getTime())?new Date():created,timezone);return {id,title,body,time,recurrence,days,customEvery,customUnit,reminder,createdAt,active:raw?.active!==false,timezone,createdAtLocalDate:{year:p.year,month:p.month,day:p.day}};}
module.exports={getDb,configureVapid,webpush,json,methodOnly,parseBody,requireSameOrigin,cleanString,validateDeviceId,validateTimezone,normalizeReminder,nextReminderAt};
